-- Run this once in phpMyAdmin if you already imported an older schema
-- Ignore errors like "Duplicate column name" if a column already exists

USE drivesure_db;

ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN confidence_score INT DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN is_blurry TINYINT(1) DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN has_exif TINYINT(1) DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN camera_make VARCHAR(100) DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN camera_model VARCHAR(100) DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN software VARCHAR(150) DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN exif_timestamp DATETIME DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN exif_latitude DECIMAL(10,7) DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN exif_longitude DECIMAL(10,7) DEFAULT NULL;
ALTER TABLE UPLOADED_EVIDENCE ADD COLUMN analysis_notes TEXT DEFAULT NULL;
